import {
  Atom,
  BookOpen,
  Brain,
  BrainCircuit,
  Calculator,
  Car,
  ChefHat,
  ChessKnight,
  Code2,
  Cpu,
  Drum,
  Dumbbell,
  FlaskConical,
  Flower2,
  Gavel,
  Guitar,
  HandFist,
  Languages,
  Layout,
  Leaf,
  Mic,
  Music,
  Music2,
  Music3,
  Music4,
  Palette,
  Piano,
  CircleDot,
  Scissors,
  Smartphone,
  Theater,
  Volleyball,
  Waves,
  type LucideIcon,
} from "lucide-react";

const SUBJECT_ICONS: Record<string, LucideIcon> = {
  Math: Calculator,
  Anglais: Languages,
  Piano,
  "Coach sportif": Dumbbell,
  Français: Languages,
  Chant: Mic,
  "Soutien scolaire": BookOpen,
  Guitare: Guitar,
  Natation: Waves,
  "Aide aux devoirs": BookOpen,
  Tennis: CircleDot,
  Espagnol: Languages,
  Arabe: Languages,
  Physique: Atom,
  Chimie: FlaskConical,
  Japonais: Languages,
  Conduite: Car,
  Dessin: Palette,
  Italien: Languages,
  Violon: Music2,
  Chinois: Languages,
  Danse: Music,
  Batterie: Drum,
  Echecs: ChessKnight,
  Yoga: Flower2,
  "Boxe anglaise": HandFist,
  Coreen: Languages,
  Couture: Scissors,
  Russe: Languages,
  Philosophe: Brain,
  SVT: Leaf,
  Droit: Gavel,
  Musculation: Dumbbell,
  Football: CircleDot,
  Saxophone: Music3,
  Basse: Guitar,
  Violoncelle: Music4,
  Informatique: Cpu,
  Cuisine: ChefHat,
  Pilates: Flower2,
  Padel: Volleyball,
  Théatre: Theater,
  Musique: Music,
  "Intelligence artificielle": BrainCircuit,
  "Application mobile": Smartphone,
  Wordpress: Layout,
  Nextjs: Code2,
};

export function SubjectIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = SUBJECT_ICONS[name] ?? BookOpen;
  return <Icon className={className} />;
}
