insert into public.subjects (name) values
  ('Math'),
  ('Anglais'),
  ('Piano'),
  ('Coach sportif'),
  ('Français'),
  ('Chant'),
  ('Soutien scolaire'),
  ('Guitare'),
  ('Natation'),
  ('Aide aux devoirs'),
  ('Tennis'),
  ('Espagnol'),
  ('Arabe'),
  ('Physique'),
  ('Chimie'),
  ('Japonais'),
  ('Conduite'),
  ('Dessin'),
  ('Italien'),
  ('Violon'),
  ('Chinois'),
  ('Danse'),
  ('Batterie'),
  ('Echecs'),
  ('Yoga'),
  ('Boxe anglaise'),
  ('Coreen'),
  ('Couture'),
  ('Russe'),
  ('Philosophe'),
  ('SVT'),
  ('Droit'),
  ('Musculation'),
  ('Football'),
  ('Saxophone'),
  ('Basse'),
  ('Violoncelle'),
  ('Informatique'),
  ('Cuisine'),
  ('Pilates'),
  ('Padel'),
  ('Théatre'),
  ('Musique'),
  ('Intelligence artificielle'),
  ('Application mobile'),
  ('Wordpress'),
  ('Nextjs')
on conflict (name) do nothing;
